baseURL = 'https://ricardoantonio.com/'
languageCode = 'es'
title = 'Ricardo Antonio'
defaultContentLanguage = 'es'
removePathAccents = true
disqusShortname = 'ricardoantoniodev'

[social]
  twitter = 'rantoniodev'

[params]
  twitter = 'https://twitter.com/rantoniodev'
  github = 'https://github.com/ricardoantonio'
  description = "Soy un Desarrollador Web apasionado por la programación, en constante proceso de aprendizaje y deseando poder colaborar contigo en cualquier proyecto que tengas en mente. Este es mi sitio web personal."

[menu]
[[menu.main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 20
[[menu.main]]
  name = 'Acerca de'
  pageRef = '/about'
  weight = 30
[[menu.main]]
  name = 'Contacto'
  pageRef = '/contact'
  weight = 40
[[menu.legal]]
  name='Política de Privacidad'
  pageRef='/privacy'
  weight=10
  

[languages]
  [languages.es]
    languageName = 'Español'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2
    [languages.en.params]
      description = "I'm a Web Developer passionate about coding, constantly learning and looking forward to collaborating with you on any project you have in mind. This is my personal website."
    [[languages.en.menu.main]]
      name="Blog"
      pageRef='/blog'
      weight=20
    [[languages.en.menu.main]]
        name="About"
        pageRef='/about'
        weight=30
    [[languages.en.menu.main]]
        name="Contact"
        pageRef='/contact'
        weight=40
    [[languages.en.menu.legal]]
        name='Privacy Policy'
        pageRef='/privacy'
        weight=10
